### ISSUE TITLE
Include the TFT UI Overlay Skins (for Streamers)

### ISSUE THREAD

**Issue by Bonifatius94** [Jarr0d161/TeamFightChaticts#13]

**Comment by Flanivia** [comment]
> @Jarr0d161 Can you please ask the graphics designer to contribute the TFT overlay skins (if he/she is fine with publishing it)? 😉

Hello there, ofc guys! Im really enjoying you bringing my Idea to a next level! Incredible work already. @Jarr0d161 You did really well!

Since i cant contribute anyting coding related, feel free to ask me for some designing Tasks like Overlays, Menus and Visualizations! Im always down to help where i can.

![UnterlageTFT](https://user-images.githubusercontent.com/62342585/172362075-b41c93cf-a768-4066-83f3-c21b953e4722.png)

**Comment by Bonifatius94** [comment]
> Hello there, ofc guys! Im really enjoying you bringing my Idea to a next level! Incredible work already.

Thank you a lot. I'm going to upload your file on GitHub. Do you know whether the skins changed for the newly released TFT set 7.0? :wink:

Maybe at a later project stage we can think about embedding your overlay into a Tkinter UI that's augmenting the TFT game client. Then, there'll be no streaming scene setup required either.

Proof-of-Concept research:
- make Tkinter window transparent: https://stackoverflow.com/questions/19080499/transparent-background-in-a-tkinter-window
- make Tkinter window clickt-hrough: https://stackoverflow.com/questions/61114145/tying-to-set-non-interactable-click-through-overlay-with-tkinter
- **resume**: seems to be possible with some effort and will

**Comment by Flanivia** [comment]
I have not looked into TFT for a long time myself due to my studies but in the past set-swaps some skins always changed. 

Sounds like a good Idea, im going to start reading myself into it to make sure im ready when we reach the later project stage.
